### PR TITLE
Fix stale output when outputHeight changes from above stdout.rows to below stdout.rows

### LINKED ISSUE #585: Output terminal isn't cleared when second to last frame is taller than terminal
Hi,
As per description, I noticed that the terminal is correctly cleared if the last frame output is taller than the terminal window, however, if the last frame is shorter, the second to last frame isn't cleared. Here's a video to demonstrate this:

https://user-images.githubusercontent.com/151725/235908525-e94e1955-4663-425d-a2f6-4430200365be.mp4

I would expect ink to not show the list after pressing enter. Is this expected behavior?

For now I've littered my code with things like this, but I would expect Ink to handle such scenarios.

```ts
if (stdout && wrapperHeight >= stdout.rows - 1) {
  stdout.write(ansiEscapes.clearTerminal)
}

setSomething(false)
```

Where `wrapperHeight` is the height of the `Box` containing everything.

Code to reproduce (make your terminal window height less than 20 lines):

```ts
import React, { useState } from 'react';
import { render, Text, Box, useInput } from 'ink';

function ClearTerminalBug() {
  const lines = [];

  for (let i = 1; i <= 20; i++) {
    lines.push(`line ${i}`);
  }

  const [done, setDone] = useState(false)

  useInput((_input, key) => {
    if (key.return) {
      setDone(true)
    }
  });

  return done ? <Text>done</Text> : <Box flexDirection="column">
    {lines.map((line, index) => (
      <Text key={index}>{line}</Text>
    ))}
  </Box>
}

render(
  <ClearTerminalBug />
)
```

Reproduction repo https://github.com/matteodepalo/clear-terminal

### PR DESCRIPTION
**Pull request by thkim1011**
When the outputHeight goes from a value ` >= stdout.rows` to a value `< stdout.rows` in between re-render, it is possible that the old content is not completely removed from the terminal. 

This happens for three reasons
1. We actually want to consider the previous output height when deciding to entirely clear the terminal or only delete several lines. If the current output has a `height >= stdout.rows`, but we only need to clear the previous render's output, there's no point in writing `ansiEscapes.clearTerminal`. Similarly, if the current output has a `height < stdout.rows` but the previous output exceeded `stdout.rows`, then writing `ansiEscapes.eraseLines(previousLineCount)` won't clear all of the old output.
2. `this.log.clear()` doesn't actually track the height of the output if we rendered via the `outputHeight >= this.options.stdout.rows` conditional. I've added a helper `LogUpdate.sync` to keep it in sync.
3. The `outputHeight >= this.options.stdout.rows` conditional differs slightly in behavior to `this.log` in that it does not append a newline at the end.

Addressing all three of these points fixes the bug.

To test, I verified locally using a small example, and I've also added a test (see "erase screen where state changes in small viewport") which fails on master but passes in this branch.

Fixes #585

### CODE REVIEW

File: src/devtools-window-polyfill.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@ import ws from 'ws';
 const customGlobal = global as any;
 
 // These things must exist before importing `react-devtools-core`
+// eslint-disable-next-line n/no-unsupported-features/node-builtins
```
Comment (thkim1011) [inline src/devtools-window-polyfill.ts:8]: Unclear why this lint error just started to appear, but should be safe to ignore.

**Comment by thkim1011** [comment]
Correct me if I'm wrong but I think my PR fixes https://github.com/vadimdemedes/ink/issues/585.

**Comment by thkim1011** [comment]
@sindresorhus can I get a re-run of the ci?

**Comment by thkim1011** [comment]
@sindresorhus just a heads up that this is ready for review.
